
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xtrinity.h"

/*
* The configuration table for devices
*/

XTrinity_Config XTrinity_ConfigTable[XPAR_XTRINITY_NUM_INSTANCES] =
{
	{
		XPAR_TRINITY_0_DEVICE_ID,
		XPAR_TRINITY_0_S_AXI_CONTROL_BASEADDR
	}
};


