
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xiicps.h"

/*
* The configuration table for devices
*/

XIicPs_Config XIicPs_ConfigTable[XPAR_XIICPS_NUM_INSTANCES] =
{
	{
		XPAR_PSU_I2C_1_DEVICE_ID,
		XPAR_PSU_I2C_1_BASEADDR,
		XPAR_PSU_I2C_1_I2C_CLK_FREQ_HZ
	}
};


