
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xspips.h"

/*
* The configuration table for devices
*/

XSpiPs_Config XSpiPs_ConfigTable[XPAR_XSPIPS_NUM_INSTANCES] =
{
	{
		XPAR_PSU_SPI_1_DEVICE_ID,
		XPAR_PSU_SPI_1_BASEADDR,
		XPAR_PSU_SPI_1_SPI_CLK_FREQ_HZ
	}
};


